INSERT INTO SONG VALUES('1','Mi Gente','J Balvin','Reggae','L2',4.32);
INSERT INTO SONG VALUES('2','Feels','Calvin Harris','Dance','L1',5.12);
INSERT INTO SONG VALUES('3','Say You Wont Let Go','James Arthur','Blues','L1',3.34);
INSERT INTO SONG VALUES('4','Bailando','Enrique Iglesias','Reggae','L2',7.12);
INSERT INTO SONG VALUES('5','Issues','Julia Michaels','Blues','L1',4.53);
INSERT INTO SONG VALUES('6','Rockabye (feat. Sean Paul and Anne-Marie)','Clean Bandit','Reggae','L1',5.32);
INSERT INTO SONG VALUES('7','Despacito (feat DY)','Luis Fonsi','Dance','L2',3.43);
INSERT INTO SONG VALUES('8','Shape of You','Ed Sheeran','Pop','L1',2.42);
INSERT INTO SONG VALUES('9','Attention','Charlie Puth','Pop','L1',5.11);
INSERT INTO SONG VALUES('10','Thunder','Imagine Dragons','Blues','L1',4.22);





INSERT INTO SONGSTREAM VALUES('1000','1','/track/2rb5MvYT7ZIxbKW5hfcHx8',4529147,'1','August');
INSERT INTO SONGSTREAM VALUES('2000','2','/track/5bcTCxgc7xVfSaMV3RuVke',3282178,'1','August');
INSERT INTO SONGSTREAM VALUES('3000','3','/track/5uCax9HTNlzGybIStD3vDh',3456727,'2','January');
INSERT INTO SONGSTREAM VALUES('4000','4','/track/1a5Yu5L18qNxVhXx38njON',3656277,'2','January');
INSERT INTO SONGSTREAM VALUES('5000','5','/track/1sXUWdKx03aP9Gmzft58rt',3267716,'1','April');
INSERT INTO SONGSTREAM VALUES('6000','6','/track/5knuzwU65gJK7IF5yJsuaW',3425448,'3','April');
INSERT INTO SONGSTREAM VALUES('7000','7','/track/4aWmUDTfIPGksMNLV2rQP2',3853673,'1','June');
INSERT INTO SONGSTREAM VALUES('8000','8','/track/7qiZfU4dY1lWllzX7mPBI3',3646128,'3','June');
INSERT INTO SONGSTREAM VALUES('9000','9','/track/4iLqG9SeJSnt0cSPICSjxv',3029066,'2','July');
INSERT INTO SONGSTREAM VALUES('10000','10','/track/0tKcYR2II1VCQWT79i5NrW',2975615,'1','July');


INSERT INTO ARTIST VALUES ('A1','J Balvin','3');
INSERT INTO ARTIST VALUES ('A2','Calvin Harris','2');
INSERT INTO ARTIST VALUES ('A3','James Arthur','2');
INSERT INTO ARTIST VALUES ('A4','Enrique Iglesias','3');
INSERT INTO ARTIST VALUES ('A5','Julia Michaels','2');
INSERT INTO ARTIST VALUES ('A6','Clean Bandit','3');
INSERT INTO ARTIST VALUES ('A7','Luis Fonsi','3');
INSERT INTO ARTIST VALUES ('A8','Ed Sheeran','2');
INSERT INTO ARTIST VALUES ('A9','Charlie Puth','2');
INSERT INTO ARTIST VALUES ('A10','Imagine Dragons','2');



INSERT INTO FAVOURITESONGS VALUES ('1','2','03-02-2017');
INSERT INTO FAVOURITESONGS VALUES ('1','4','15-02-2017');
INSERT INTO FAVOURITESONGS VALUES ('1','7','01-03-2017');
INSERT INTO FAVOURITESONGS VALUES ('1','8','20-04-2017');
INSERT INTO FAVOURITESONGS VALUES ('1','1','01-08-2017');
INSERT INTO FAVOURITESONGS VALUES ('2','1','02-04-2017');
INSERT INTO FAVOURITESONGS VALUES ('2','2','03-05-2017');
INSERT INTO FAVOURITESONGS VALUES ('2','5','02-04-2017');
INSERT INTO FAVOURITESONGS VALUES ('2','7','20-07-2017');
INSERT INTO FAVOURITESONGS VALUES ('3','3','02-05-2017');
INSERT INTO FAVOURITESONGS VALUES ('3','1','20-04-2017');
INSERT INTO FAVOURITESONGS VALUES ('3','7','04-05-2017');
INSERT INTO FAVOURITESONGS VALUES ('3','8','01-08-2017');
INSERT INTO FAVOURITESONGS VALUES ('3','10','02-07-2017');

INSERT INTO ALBUM VALUES ('1','J Balvin','Spanish Hits');
INSERT INTO ALBUM VALUES ('2','Calvin Harris','Funk Wav Bounces');
INSERT INTO ALBUM VALUES ('3','James Arthur','Back From The Edge');
INSERT INTO ALBUM VALUES ('4','Enrique Iglesias','Spanish Hits');
INSERT INTO ALBUM VALUES ('5','Julia Michaels','Back From The Edge');
INSERT INTO ALBUM VALUES ('6','Clean Bandit','Funk Wav Bounces');
INSERT INTO ALBUM VALUES ('7','Luis Fonsi','Spanish Hits');
INSERT INTO ALBUM VALUES ('8','Ed Sheeran','Divide');
INSERT INTO ALBUM VALUES ('9','Charlie Puth','Funk Wav Bounces');
INSERT INTO ALBUM VALUES ('10','Imagine Dragons','Evolve');

INSERT INTO REGION VALUES ('1','Global','');
INSERT INTO REGION VALUES ('2','USA','English');
INSERT INTO REGION VALUES ('3','Spain','Spanish');
	
INSERT INTO SERVICEUSER VALUES ('1','Kunal','2');
INSERT INTO SERVICEUSER VALUES ('2','Akash','3');
INSERT INTO SERVICEUSER VALUES ('3','Saurabh','2');
